export * from './direccion-viento';
export * from './geotermometro';
export * from './nubosidad';
export * from './presion-atmosferica';
export * from './registro';
export * from './temperatura';
export * from './termometro-humedo';
export * from './termometro-seco';
export * from './visibilidad';